--!strict
return {
	[1] = { id = 1, name = "Verdant Crash Site", biomes = { "Meadow", "Forest", "Cave" }, warden = "Gaiabloom", rule = "DayNightRain" },
	[2] = { id = 2, name = "Frostbyte", biomes = { "Snowfield", "IceCave", "GeyserField" }, warden = "Skaddle", rule = "Blizzard" },
	[3] = { id = 3, name = "Neon Grid", biomes = { "Rooftops", "ServerFarm", "Undercity" }, warden = "Hephaestron", rule = "PowerSurge" },
}
